$Shares = ("\\naf01b\ENShare8\Apps",
"\\naf01b\ENShare2\Infrastructure\Cisco Phones and UM\Call Flows & Design Docs",
"\\naf01b\ENShare2\Desktop Engineering",
"\\naf01b\ENShare3\DoitsCommon",
"\\naf01b\ENShare8\Drivers",
"\\naf01b\ENShare3\Enterprise Development",
"\\naf01b\ENShare2\Forms",
"\\naf01b\ENShare3\Foundation Data Transfer",
"\\naf01b\ENShare2\IDM_AccessManager",
"\\naf01b\ENShare2\Infrastructure",
"\\naf01b\enserver4$\MiddlewareIOLinks",
"\\naf01b\ENShare8\Drivers\OldZenroot",
"\\naf01b\enserver4$\PeopleSoftIOLinks",
"\\naf01b\ENShare2\Process Guides",
"\\naf01b\ENShare2\PWS",
"\\naf01b\ENShare2\SharePoint",
"\\naf01b\ENShare7\Source Media",
"\\naf01b\ENShare2\Sparx",
"\\naf01b\ENShare2\Client Services",
"\\naf01b\ENShare2\TelePresence Issues",
"\\naf01b\ENShare8\ThinApp",
"\\naf01b\ENShare2\TS-PMO",
"\\naf01b\ENServer5\USM")